// <auto-generated />
using CadastroProdutos.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroProdutos.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CadastroProdutos.Models.DefSituacaoProduto", b =>
                {
                    b.Property<int>("SituacaoProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SituacaoProdutoId"), 1L, 1);

                    b.Property<string>("DescricaoSituacao")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("SituacaoProdutoId");

                    b.ToTable("DefSituacaoProduto");
                });

            modelBuilder.Entity("CadastroProdutos.Models.DefSituacaoProdutoEmbalagem", b =>
                {
                    b.Property<int>("SituacaoProdutoEmbalagemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SituacaoProdutoEmbalagemID"), 1L, 1);

                    b.Property<string>("DescricaoSituacao")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("SituacaoProdutoEmbalagemID");

                    b.ToTable("DefSituacaoProdutoEmbalagem");
                });

            modelBuilder.Entity("CadastroProdutos.Models.DefUnidadeComercial", b =>
                {
                    b.Property<int>("UnidadeComercialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnidadeComercialID"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.HasKey("UnidadeComercialID");

                    b.ToTable("DefUnidadeComercial");
                });

            modelBuilder.Entity("CadastroProdutos.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoID"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<decimal>("PesoLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SituacaoProdutoID")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeComercialID")
                        .HasColumnType("int");

                    b.HasKey("ProdutoID");

                    b.HasIndex("SituacaoProdutoID");

                    b.HasIndex("UnidadeComercialID");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("CadastroProdutos.Models.ProdutoEmbalagem", b =>
                {
                    b.Property<int>("ProdutoEmbalagemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoEmbalagemID"), 1L, 1);

                    b.Property<decimal>("FatorDeConversao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoID")
                        .HasColumnType("int");

                    b.Property<int>("SituacaoProdutoEmbalagemID")
                        .HasColumnType("int");

                    b.HasKey("ProdutoEmbalagemID");

                    b.HasIndex("ProdutoID");

                    b.HasIndex("SituacaoProdutoEmbalagemID");

                    b.ToTable("ProdutoEmbalagens");
                });

            modelBuilder.Entity("CadastroProdutos.Models.Produto", b =>
                {
                    b.HasOne("CadastroProdutos.Models.DefSituacaoProduto", "DefSituacaoProduto")
                        .WithMany()
                        .HasForeignKey("SituacaoProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadastroProdutos.Models.DefUnidadeComercial", "DefUnidadeComercial")
                        .WithMany()
                        .HasForeignKey("UnidadeComercialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefSituacaoProduto");

                    b.Navigation("DefUnidadeComercial");
                });

            modelBuilder.Entity("CadastroProdutos.Models.ProdutoEmbalagem", b =>
                {
                    b.HasOne("CadastroProdutos.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CadastroProdutos.Models.DefSituacaoProdutoEmbalagem", "DefSituacaoProdutoEmbalagem")
                        .WithMany()
                        .HasForeignKey("SituacaoProdutoEmbalagemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefSituacaoProdutoEmbalagem");

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
